import type { Country, Fixture, League } from "@/shared/domain";

export const demoCountries: Country[] = [
  { id: "england", name: "Inglaterra", code: "ENG", region: "Europa" },
  { id: "spain", name: "España", code: "ESP", region: "Europa" },
  { id: "argentina", name: "Argentina", code: "ARG", region: "Sudamérica" },
  { id: "japan", name: "Japón", code: "JPN", region: "Asia" },
  { id: "mexico", name: "México", code: "MEX", region: "Norteamérica" },
];

export const demoLeagues: League[] = [
  { id: "premier-league", countryId: "england", name: "Premier League", tier: "elite", season: "2026/27", coverageScore: 96 },
  { id: "laliga", countryId: "spain", name: "LaLiga", tier: "elite", season: "2026/27", coverageScore: 94 },
  { id: "primera-arg", countryId: "argentina", name: "Primera División", tier: "standard", season: "2026", coverageScore: 81 },
  { id: "j1-league", countryId: "japan", name: "J1 League", tier: "standard", season: "2026", coverageScore: 78 },
  { id: "national-league", countryId: "england", name: "National League", tier: "low", season: "2026/27", coverageScore: 54 },
  { id: "liga-mx-femenil", countryId: "mexico", name: "Liga MX Femenil", tier: "standard", season: "Clausura 2026", coverageScore: 82 },
];

export const demoFixtures: Fixture[] = [
  {
    id: "fixture-arsenal-brighton",
    countryId: "england",
    leagueId: "premier-league",
    leagueName: "Premier League",
    kickoff: "2026-05-14T19:45:00-05:00",
    status: "pre-match",
    home: {
      id: "arsenal",
      name: "Arsenal",
      form: ["W", "W", "D", "W", "L"],
      goalsFor: 41,
      goalsAgainst: 19,
      xgFor: 38.6,
      xgAgainst: 20.7,
      tablePosition: 2,
      restDays: 5,
      travelKm: 0,
      motivation: 86,
      keyPlayer: "Bukayo Saka",
      keyPlayerStatus: "available",
      squadRotationRisk: 18,
      pointsTotal: 64,
      matchesPlayed: 28,
    },
    away: {
      id: "brighton",
      name: "Brighton",
      form: ["D", "W", "L", "D", "W"],
      goalsFor: 32,
      goalsAgainst: 29,
      xgFor: 33.4,
      xgAgainst: 31.8,
      tablePosition: 8,
      restDays: 4,
      travelKm: 95,
      motivation: 68,
      keyPlayer: "Kaoru Mitoma",
      keyPlayerStatus: "available",
      squadRotationRisk: 28,
      pointsTotal: 42,
      matchesPlayed: 28,
    },
    coverage: { tier: "elite", hasLineups: true, hasOdds: true, hasXg: true, hasInjuries: true, hasReferee: true, hasH2H: true, hasMomentum: true },
    market: { homeWinOdds: 1.76, drawOdds: 3.9, awayWinOdds: 4.7, over15Odds: 1.12, over25Odds: 1.82, under35Odds: 1.48, bttsYesOdds: 1.74, bttsNoOdds: 2.05, ahHomeMinus1: 2.20, ahAwayPlus1: 1.62, exactScore: [], firstGoalScorer: [] },
    context: { derby: false, mustWinHome: true, mustWinAway: false, lowDivision: false, weatherRisk: "low", playoff: false, relegationRisk: 0, rivalRivalry: false, copaVsLeague: false, prizeMoney: 0, psychologicalPressure: 42, underdogFreedom: 35, favoriteParalysis: 18 },
  },
  {
    id: "fixture-river-lanus",
    countryId: "argentina",
    leagueId: "primera-arg",
    leagueName: "Primera División",
    kickoff: "2026-05-14T18:30:00-05:00",
    status: "pre-match",
    home: {
      id: "river",
      name: "River Plate",
      form: ["W", "D", "W", "W", "D"],
      goalsFor: 29,
      goalsAgainst: 15,
      xgFor: 27.2,
      xgAgainst: 16.6,
      tablePosition: 1,
      restDays: 3,
      travelKm: 0,
      motivation: 82,
      keyPlayer: "Esequiel Barco",
      keyPlayerStatus: "available",
      squadRotationRisk: 22,
      pointsTotal: 44,
      matchesPlayed: 18,
    },
    away: {
      id: "lanus",
      name: "Lanús",
      form: ["L", "D", "W", "L", "D"],
      goalsFor: 17,
      goalsAgainst: 21,
      xgFor: 18.4,
      xgAgainst: 22.2,
      tablePosition: 12,
      restDays: 6,
      travelKm: 28,
      motivation: 61,
      keyPlayer: "Leandro Díaz",
      keyPlayerStatus: "doubtful",
      squadRotationRisk: 40,
      pointsTotal: 22,
      matchesPlayed: 18,
    },
    coverage: { tier: "standard", hasLineups: false, hasOdds: true, hasXg: true, hasInjuries: false, hasReferee: true, hasH2H: false, hasMomentum: false },
    market: { homeWinOdds: 1.64, drawOdds: 3.7, awayWinOdds: 5.4, over15Odds: 1.14, over25Odds: 2.05, under35Odds: 1.34, bttsYesOdds: 1.96, bttsNoOdds: 1.82, ahHomeMinus1: 1.95, ahAwayPlus1: 1.85, exactScore: [], firstGoalScorer: [] },
    context: { derby: false, mustWinHome: true, mustWinAway: false, lowDivision: false, weatherRisk: "medium", playoff: false, relegationRisk: 10, rivalRivalry: false, copaVsLeague: false, prizeMoney: 0, psychologicalPressure: 28, underdogFreedom: 48, favoriteParalysis: 12 },
  },
  {
    id: "fixture-oldham-york",
    countryId: "england",
    leagueId: "national-league",
    leagueName: "National League",
    kickoff: "2026-05-14T14:00:00-05:00",
    status: "pre-match",
    home: {
      id: "oldham",
      name: "Oldham Athletic",
      form: ["W", "L", "D", "W", "L"],
      goalsFor: 22,
      goalsAgainst: 24,
      xgFor: 20.1,
      xgAgainst: 25.8,
      tablePosition: 9,
      restDays: 3,
      travelKm: 0,
      motivation: 64,
      keyPlayer: "Mike Fondop",
      keyPlayerStatus: "available",
      squadRotationRisk: 30,
      pointsTotal: 36,
      matchesPlayed: 24,
    },
    away: {
      id: "york",
      name: "York City",
      form: ["W", "W", "W", "D", "W"],
      goalsFor: 35,
      goalsAgainst: 20,
      xgFor: 31.6,
      xgAgainst: 21.5,
      tablePosition: 2,
      restDays: 3,
      travelKm: 142,
      motivation: 88,
      keyPlayer: "Lenell John-Lewis",
      keyPlayerStatus: "available",
      squadRotationRisk: 15,
      pointsTotal: 52,
      matchesPlayed: 24,
    },
    coverage: { tier: "low", hasLineups: false, hasOdds: true, hasXg: false, hasInjuries: false, hasReferee: false, hasH2H: false, hasMomentum: false },
    market: { homeWinOdds: 3.1, drawOdds: 3.35, awayWinOdds: 2.18, over15Odds: 1.22, over25Odds: 1.92, under35Odds: 1.42, bttsYesOdds: 1.73, bttsNoOdds: 2.05, ahHomeMinus1: 3.40, ahAwayPlus1: 1.30, exactScore: [], firstGoalScorer: [] },
    context: { derby: false, mustWinHome: false, mustWinAway: true, lowDivision: true, weatherRisk: "high", playoff: false, relegationRisk: 18, rivalRivalry: false, copaVsLeague: false, prizeMoney: 0, psychologicalPressure: 55, underdogFreedom: 60, favoriteParalysis: 25 },
  },
  {
    id: "fixture-juarez-monterrey-f",
    countryId: "mexico",
    leagueId: "liga-mx-femenil",
    leagueName: "Liga MX Femenil",
    kickoff: "2026-05-15T18:00:00-05:00",
    status: "pre-match",
    home: {
      id: "juarez-f",
      name: "FC Juarez Femenil",
      form: ["D", "W", "L", "D", "L"],
      goalsFor: 15,
      goalsAgainst: 22,
      xgFor: 13.8,
      xgAgainst: 24.1,
      tablePosition: 12,
      restDays: 4,
      travelKm: 0,
      motivation: 58,
      keyPlayer: "Daniela Espinoza",
      keyPlayerStatus: "available",
      squadRotationRisk: 35,
      pointsTotal: 14,
      matchesPlayed: 11,
    },
    away: {
      id: "monterrey-f",
      name: "Rayadas de Monterrey F",
      form: ["W", "W", "W", "D", "W"],
      goalsFor: 34,
      goalsAgainst: 10,
      xgFor: 36.2,
      xgAgainst: 11.4,
      tablePosition: 1,
      restDays: 3,
      travelKm: 1028,
      motivation: 76,
      keyPlayer: "Christina Burkenroad",
      keyPlayerStatus: "available",
      squadRotationRisk: 42,
      pointsTotal: 31,
      matchesPlayed: 11,
    },
    coverage: {
      tier: "standard",
      hasLineups: false,
      hasOdds: true,
      hasXg: true,
      hasInjuries: true,
      hasReferee: true,
      hasH2H: true,
      hasMomentum: true,
    },
    market: {
      homeWinOdds: 5.80,
      drawOdds: 3.95,
      awayWinOdds: 1.55,
      over15Odds: 1.18,
      over25Odds: 1.72,
      under35Odds: 1.38,
      bttsYesOdds: 2.10,
      bttsNoOdds: 1.70,
      ahHomeMinus1: 2.40,
      ahAwayPlus1: 1.58,
      exactScore: [
        { score: "0-2", odds: 8.50 },
        { score: "0-3", odds: 11.00 },
        { score: "1-2", odds: 9.50 },
      ],
      firstGoalScorer: [
        { player: "Christina Burkenroad", odds: 4.50 },
        { player: "Rebeca Bernal", odds: 12.00 },
        { player: "Daniela Espinoza", odds: 8.00 },
      ],
    },
    context: {
      derby: false,
      mustWinHome: false,
      mustWinAway: false,
      lowDivision: false,
      weatherRisk: "low",
      playoff: false,
      relegationRisk: 25,
      rivalRivalry: false,
      copaVsLeague: false,
      prizeMoney: 500,
      psychologicalPressure: 38,
      underdogFreedom: 72,
      favoriteParalysis: 22,
    },
    h2h: [
      {
        date: "2025-10-15",
        home: "Rayadas de Monterrey F",
        away: "FC Juarez Femenil",
        homeGoals: 4,
        awayGoals: 0,
        competition: "Liga MX Femenil",
        venue: "Estadio BBVA",
        firstHalfHome: 2,
        firstHalfAway: 0,
        homeXg: 2.8,
        awayXg: 0.3,
        cards: 3,
        corners: 8,
        dominantTeam: "Monterrey F",
      },
      {
        date: "2025-04-22",
        home: "FC Juarez Femenil",
        away: "Rayadas de Monterrey F",
        homeGoals: 0,
        awayGoals: 3,
        competition: "Liga MX Femenil",
        venue: "Estadio Olímpico Benito Juárez",
        firstHalfHome: 0,
        firstHalfAway: 1,
        homeXg: 0.4,
        awayXg: 2.5,
        cards: 2,
        corners: 6,
        dominantTeam: "Monterrey F",
      },
      {
        date: "2024-09-28",
        home: "Rayadas de Monterrey F",
        away: "FC Juarez Femenil",
        homeGoals: 2,
        awayGoals: 1,
        competition: "Liga MX Femenil",
        venue: "Estadio BBVA",
        firstHalfHome: 1,
        firstHalfAway: 1,
        homeXg: 2.1,
        awayXg: 0.8,
        cards: 4,
        corners: 9,
        dominantTeam: "Monterrey F",
      },
      {
        date: "2024-03-08",
        home: "FC Juarez Femenil",
        away: "Rayadas de Monterrey F",
        homeGoals: 1,
        awayGoals: 2,
        competition: "Liga MX Femenil",
        venue: "Estadio Olímpico Benito Juárez",
        firstHalfHome: 0,
        firstHalfAway: 2,
        homeXg: 0.6,
        awayXg: 1.9,
        cards: 3,
        corners: 7,
        dominantTeam: "Monterrey F",
      },
      {
        date: "2023-07-15",
        home: "Rayadas de Monterrey F",
        away: "FC Juarez Femenil",
        homeGoals: 5,
        awayGoals: 0,
        competition: "Liga MX Femenil",
        venue: "Estadio BBVA",
        firstHalfHome: 3,
        firstHalfAway: 0,
        homeXg: 3.5,
        awayXg: 0.1,
        cards: 1,
        corners: 11,
        dominantTeam: "Monterrey F",
      },
    ],
    referee: {
      name: "Karen Hernández",
      avgCards: 3.8,
      avgPenalties: 0.3,
      strictness: "medium",
      homeBias: 2,
      controversyHistory: [
        "2025-Clausura: Penal dudoso en Tigres vs America",
        "2025-Apertura: 3 expulsiones en partido de liguilla",
      ],
      lastMatches: 45,
    },
    squad: {
      home: {
        injuries: [
          { player: "Miah Zuazua", position: "Defensa", status: "Lesionada (rodilla)", impact: 7 },
          { player: "Yazmin Quezada", position: "Mediocampo", status: "Dudosa (muscular)", impact: 5 },
        ],
        suspensions: [],
        lastLineup: ["Góngora", "Rodríguez", "Zuazua", "Cruz", "García", "Quezada", "Ortiz", "López", "Morales", "Espinoza", "Hernández"],
        tacticalChangeRisk: 0,
      },
      away: {
        injuries: [
          { player: "Diana García", position: "Defensa", status: "Lesionada (tobillo)", impact: 3 },
        ],
        suspensions: [],
        lastLineup: ["Godínez", "Bernal", "García", "Evangelista", "Delgado", "Calderón", "Evangelista", "Valdez", "Rodríguez", "Burkenroad", "Martínez"],
        tacticalChangeRisk: 0,
      },
    },
    historicalOutliers: [
      { date: "2024-11-03", match: "Puebla F 2-1 Tigres F", description: "Colista Puebla vence a líder Tigres — evento 1 en 50", probability: 4, category: "upset" },
      { date: "2024-08-17", match: "Mazatlan F 1-1 America F", description: "Último empata con primero tras 2 expulsiones", probability: 6, category: "cards" },
      { date: "2025-03-22", match: "Santos F 3-2 Chivas F", description: "12° vence a 3° con 2 penales polémicos", probability: 5, category: "referee" },
    ],
    socialSentiment: { homePositive: 18, awayPositive: 72, neutral: 10 },
  },
  {
    id: "fixture-finished-demo",
    countryId: "england",
    leagueId: "premier-league",
    leagueName: "Premier League",
    kickoff: "2026-05-10T15:00:00-05:00",
    status: "final",
    home: {
      id: "manchester-city",
      name: "Manchester City",
      form: ["W", "W", "W", "D", "W"],
      goalsFor: 58,
      goalsAgainst: 22,
      xgFor: 54.1,
      xgAgainst: 23.9,
      tablePosition: 1,
      restDays: 5,
      travelKm: 0,
      motivation: 88,
      keyPlayer: "Erling Haaland",
      keyPlayerStatus: "available",
      squadRotationRisk: 16,
      pointsTotal: 72,
      matchesPlayed: 30,
    },
    away: {
      id: "fulham",
      name: "Fulham",
      form: ["L", "D", "W", "L", "D"],
      goalsFor: 28,
      goalsAgainst: 36,
      xgFor: 30.2,
      xgAgainst: 34.5,
      tablePosition: 12,
      restDays: 4,
      travelKm: 320,
      motivation: 60,
      keyPlayer: "Raul Jimenez",
      keyPlayerStatus: "available",
      squadRotationRisk: 30,
      pointsTotal: 38,
      matchesPlayed: 30,
    },
    coverage: { tier: "elite", hasLineups: true, hasOdds: true, hasXg: true, hasInjuries: true, hasReferee: true, hasH2H: true, hasMomentum: true },
    market: { homeWinOdds: 1.42, drawOdds: 4.6, awayWinOdds: 7.2, over15Odds: 1.10, over25Odds: 1.65, under35Odds: 1.55, bttsYesOdds: 1.85, bttsNoOdds: 1.95, ahHomeMinus1: 1.85, ahAwayPlus1: 1.95, exactScore: [], firstGoalScorer: [] },
    context: { derby: false, mustWinHome: true, mustWinAway: false, lowDivision: false, weatherRisk: "low", playoff: false, relegationRisk: 0, rivalRivalry: false, copaVsLeague: false, prizeMoney: 0, psychologicalPressure: 30, underdogFreedom: 50, favoriteParalysis: 12 },
    result: {
      homeGoals: 3,
      awayGoals: 1,
      totalGoals: 4,
      bttsActual: true,
      firstHalfHome: 2,
      firstHalfAway: 0,
      corners: { home: 7, away: 3 },
      cards: { yellowHome: 1, yellowAway: 3, redHome: 0, redAway: 0 },
      penaltyAwarded: false,
      scorers: [
        { player: "Demo Striker A", team: "home", minute: 14 },
        { player: "Demo Striker A", team: "home", minute: 38 },
        { player: "Demo Winger B", team: "home", minute: 67 },
        { player: "Demo Forward C", team: "away", minute: 81 },
      ],
      bookedPlayers: ["Demo Defender X", "Demo Midfielder Y"],
    },
  },
];
