import type { Fixture } from "@/shared/domain";
import type { ApiLiveEvent, ApiLiveStatistic } from "@/backend/lib/providers/api-football-provider";

export const demoLiveFixtures: Fixture[] = [
  {
    id: "demo-live-arsenal-brighton",
    countryId: "england",
    leagueId: "premier-league",
    leagueName: "Premier League",
    leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    kickoff: "2026-05-20T19:45:00-05:00",
    elapsed: 67,
    status: "live",
    result: {
      homeGoals: 2,
      awayGoals: 1,
      totalGoals: 3,
      bttsActual: true,
      firstHalfHome: 1,
      firstHalfAway: 0,
    },
    home: {
      id: "arsenal",
      name: "Arsenal",
      logo: "https://media.api-sports.io/football/teams/42.png",
      form: ["W", "W", "D", "W", "L"],
      goalsFor: 41,
      goalsAgainst: 19,
      xgFor: 38.6,
      xgAgainst: 20.7,
      tablePosition: 2,
      restDays: 5,
      travelKm: 0,
      motivation: 86,
      keyPlayer: "Bukayo Saka",
      keyPlayerStatus: "available",
      squadRotationRisk: 18,
      pointsTotal: 64,
      matchesPlayed: 28,
    },
    away: {
      id: "brighton",
      name: "Brighton",
      logo: "https://media.api-sports.io/football/teams/51.png",
      form: ["D", "W", "L", "D", "W"],
      goalsFor: 32,
      goalsAgainst: 29,
      xgFor: 33.4,
      xgAgainst: 31.8,
      tablePosition: 8,
      restDays: 4,
      travelKm: 95,
      motivation: 68,
      keyPlayer: "Kaoru Mitoma",
      keyPlayerStatus: "available",
      squadRotationRisk: 28,
      pointsTotal: 42,
      matchesPlayed: 28,
    },
    coverage: {
      tier: "elite",
      hasLineups: true,
      hasOdds: true,
      hasXg: true,
      hasInjuries: true,
      hasReferee: true,
      hasH2H: true,
      hasMomentum: true,
    },
    market: {
      homeWinOdds: 1.45,
      drawOdds: 4.6,
      awayWinOdds: 6.2,
      over15Odds: 1.08,
      over25Odds: 1.35,
      under35Odds: 1.72,
      bttsYesOdds: 1.55,
      bttsNoOdds: 2.35,
      ahHomeMinus1: 2.05,
      ahAwayPlus1: 1.78,
      exactScore: [],
      firstGoalScorer: [],
    },
    context: {
      derby: false,
      mustWinHome: true,
      mustWinAway: false,
      lowDivision: false,
      weatherRisk: "low",
      playoff: false,
      relegationRisk: 0,
      rivalRivalry: false,
      copaVsLeague: false,
      prizeMoney: 0,
      psychologicalPressure: 42,
      underdogFreedom: 35,
      favoriteParalysis: 18,
    },
  },
  {
    id: "demo-live-real-barca",
    countryId: "spain",
    leagueId: "laliga",
    leagueName: "LaLiga",
    leagueLogo: "https://media.api-sports.io/football/leagues/140.png",
    kickoff: "2026-05-20T21:00:00+02:00",
    elapsed: 34,
    status: "live",
    result: {
      homeGoals: 1,
      awayGoals: 1,
      totalGoals: 2,
      bttsActual: true,
      firstHalfHome: 1,
      firstHalfAway: 1,
    },
    home: {
      id: "real-madrid",
      name: "Real Madrid",
      logo: "https://media.api-sports.io/football/teams/541.png",
      form: ["W", "W", "W", "D", "W"],
      goalsFor: 55,
      goalsAgainst: 22,
      xgFor: 52.1,
      xgAgainst: 24.3,
      tablePosition: 1,
      restDays: 6,
      travelKm: 0,
      motivation: 92,
      keyPlayer: "Vinícius Júnior",
      keyPlayerStatus: "available",
      squadRotationRisk: 12,
      pointsTotal: 78,
      matchesPlayed: 34,
    },
    away: {
      id: "barcelona",
      name: "Barcelona",
      logo: "https://media.api-sports.io/football/teams/529.png",
      form: ["W", "D", "W", "W", "W"],
      goalsFor: 58,
      goalsAgainst: 25,
      xgFor: 54.8,
      xgAgainst: 26.1,
      tablePosition: 2,
      restDays: 6,
      travelKm: 620,
      motivation: 94,
      keyPlayer: "Robert Lewandowski",
      keyPlayerStatus: "available",
      squadRotationRisk: 10,
      pointsTotal: 76,
      matchesPlayed: 34,
    },
    coverage: {
      tier: "elite",
      hasLineups: true,
      hasOdds: true,
      hasXg: true,
      hasInjuries: true,
      hasReferee: true,
      hasH2H: true,
      hasMomentum: true,
    },
    market: {
      homeWinOdds: 2.35,
      drawOdds: 3.4,
      awayWinOdds: 2.9,
      over15Odds: 1.15,
      over25Odds: 1.62,
      under35Odds: 1.55,
      bttsYesOdds: 1.48,
      bttsNoOdds: 2.55,
      ahHomeMinus1: 3.1,
      ahAwayPlus1: 1.42,
      exactScore: [],
      firstGoalScorer: [],
    },
    context: {
      derby: true,
      mustWinHome: true,
      mustWinAway: true,
      lowDivision: false,
      weatherRisk: "low",
      playoff: false,
      relegationRisk: 0,
      rivalRivalry: true,
      copaVsLeague: false,
      prizeMoney: 0,
      psychologicalPressure: 88,
      underdogFreedom: 20,
      favoriteParalysis: 35,
    },
  },
];

export const demoLiveEvents: Record<string, ApiLiveEvent[]> = {
  "demo-live-arsenal-brighton": [
    { time: 12, team: "Arsenal", teamLogo: "", player: "Bukayo Saka", type: "Goal", detail: "Normal Goal" },
    { time: 28, team: "Brighton", teamLogo: "", player: "Kaoru Mitoma", type: "Card", detail: "Yellow Card" },
    { time: 41, team: "Arsenal", teamLogo: "", player: "Gabriel Martinelli", type: "Goal", detail: "Normal Goal" },
    { time: 58, team: "Brighton", teamLogo: "", player: "João Pedro", type: "Goal", detail: "Penalty" },
  ],
  "demo-live-real-barca": [
    { time: 8, team: "Real Madrid", teamLogo: "", player: "Vinícius Júnior", type: "Goal", detail: "Normal Goal" },
    { time: 19, team: "Barcelona", teamLogo: "", player: "Robert Lewandowski", type: "Goal", detail: "Normal Goal" },
    { time: 31, team: "Barcelona", teamLogo: "", player: "Pedri", type: "Card", detail: "Yellow Card" },
  ],
};

export const demoLiveStatistics: Record<string, ApiLiveStatistic[]> = {
  "demo-live-arsenal-brighton": [
    { type: "Shots on Goal", home: "6", away: "3" },
    { type: "Total Shots", home: "12", away: "8" },
    { type: "Ball Possession", home: "58%", away: "42%" },
    { type: "Corner Kicks", home: "5", away: "2" },
    { type: "Fouls", home: "9", away: "11" },
  ],
  "demo-live-real-barca": [
    { type: "Shots on Goal", home: "4", away: "4" },
    { type: "Total Shots", home: "9", away: "10" },
    { type: "Ball Possession", home: "49%", away: "51%" },
    { type: "Corner Kicks", home: "3", away: "4" },
    { type: "Fouls", home: "7", away: "6" },
  ],
};
